<?php
$title = 'Agregar una pregunta';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$pregunta = $form->get('texto');
$pregunta->setAttribute('class', 'form-control');
$pregunta->setAttribute('placeholder', 'Texto de la pregunta');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$id_examen=$form->getValue('id_examen');
//$form->setAttribute('action', $this->url('pregunta', ['action' => 'add', 'id_pregunta' => $id_examen]));
//$form->get('id_examen')->getValue()
	//$this->formHidden($form->get('id_examen'))
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($pregunta) ?>
    <?= $this->formElement($pregunta) ?>
    <?= $this->formElementErrors()->render($pregunta, ['class' => 'help-block']) ?>
</div>


<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id_pregunta'));
echo $this->formHidden($form->get('id_examen'));
echo $this->form()->closeTag();