<?php

$title = 'Borrar pregunta';
$url   = $this->url('pregunta', ['action' => 'delete', 'id_pregunta' => $id_pregunta]);

$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    ¿Está seguro de borrar esta pregunta?
    "<?= $this->escapeHtml($pregunta->texto) ?>"
</p>
<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id_pregunta" value="<?= (int) $pregunta->id_pregunta ?>"/>
        <input type="submit" class="btn btn-danger" name="del" value="Si" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>