<?php
//$id_pregunta = $this->returnPregunta();
$title = 'Presentación de examen';
$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1>


<h3>Da clic en el nombre de la materia para presentar examen</h3>

    <?php 
    
   
    foreach ($examenes as $examen) { ?>
    
            <a href="<?= $this->url('alumno', ['action' => 'edit', 'id_examen' => $examen->id])?>"> <?= $this->escapeHtml($examen->materia) ?></a>
            <br>


    <?php } ?>
