<?php
$title = 'Agregar un examen';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$examen = $form->get('materia');
$examen->setAttribute('class', 'form-control');
$examen->setAttribute('placeholder', 'Nombre de la materia');

// This provides a default CSS class and placeholder text for the artist element:
$unidad = $form->get('unidad');
$unidad->setAttribute('class', 'form-control');
$unidad->setAttribute('placeholder', 'Unidad que se evalúa');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('examen', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($examen) ?>
    <?= $this->formElement($examen) ?>
    <?= $this->formElementErrors()->render($examen, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($unidad) ?>
    <?= $this->formElement($unidad) ?>
    <?= $this->formElementErrors()->render($unidad, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();